### PR TITLE
Add an uninstall script for the module

### PR DESCRIPTION
**Pull request by DrowningElysium**
Issue 4137 in gitlab.

Test with command: bin/magento module:uninstall --remove-data Dealer4dealer_Xcore

### CODE REVIEW

**Comment by hostep** [comment]
Out of curiosity: why did all file permissions change from 644 to 755? This sounds like a mistake to me?

**Comment by hostep** [comment]
@Tjab, @HenriNijborg: any idea? I just noticed this again today, those permission changes introduced here seem wrong to me? PHP source code files should not be executable.

**Comment by HenriNijborg** [comment]
@hostep The file permission changes will be reverted in https://github.com/dealer4dealer/magento2-restapi/pull/39 , version 2.6.1 of this extension. Sorry for missing your previous comment.

**Comment by hostep** [comment]
Thanks, and no problem! 🙂

**Pull request merged**
